# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sura',
            fields=[
                ('index', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Sura')),
            ],
        ),
        migrations.AddField(
            model_name='ayah',
            name='sura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayat', to='quran_text.Sura'),
        ),
    ]
