# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quran_text', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tafseer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='TafseerText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Tafseer')),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran_text.Ayah')),
                ('tafseer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran_tafseer.Tafseer')),
            ],
        ),
    ]
