# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran_tafseer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tafseer',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='tafseer',
            name='book_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Book Name'),
        ),
        migrations.AddField(
            model_name='tafseer',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Language'),
        ),
    ]
